add_newline = true
command_timeout = 1000
format = """$os$directory$git_branch$git_status$git_metrics$fill$bun$nodejs$golang$cmd_duration$line_break$character"""

[character]
success_symbol = "[](bold purple)"
error_symbol = "[](bold red)"

[hostname]
ssh_only = false
style = "purple bold"
format = "[$hostname]($style) "

[fill]
symbol = " "

[os]
format = '[$symbol](bold white)'
disabled = false

[os.symbols]
Macos = ' '

[directory]
truncation_length = 1
truncation_symbol = "…/"
home_symbol = "󰋜 ~"
read_only_style = "197"
read_only = "  "
format = ' [$path]($style)[$read_only]($read_only_style) '
style = "purple bold"

[git_branch]
symbol = " "
format = ' [$symbol$branch]($style) '
truncation_symbol = "…/"
style = "bold green"

[git_metrics]
disabled = false

[git_status]
format = '([ \( $all_status$ahead_behind\)]($style) )'
style = "red green"
conflicted = " [${count}](red) "
up_to_date = "[ up-to-date](green) "
untracked = "[ ${count}](red) "
ahead = "[ ${count}]"
diverged = " ${ahead_count}  ${behind_count}"
behind = " ${count}"
# stashed = "[ ${count}](green) "
modified = "[ ${count}](yellow) "
staged = "[ ${count}](green) "
renamed = "[ ${count}](yellow)"
deleted = "[ ${count}](red) "

[time]
disabled = false
format = "[$time]($style) "
use_12hr = true
time_format = '%R'

[bun]
symbol = ' '
disabled = false
format = "[$symbol($version )](bold #fbf0df) "

[nodejs]
symbol = ' '
disabled = false
format = "[$symbol($version )](bold #74ac63) "

[golang]
symbol = ' '
disabled = false
format = "[$symbol($version )](bold #00a7d0) "


[cmd_duration]
min_time = 200
format = '[$duration](bold yellow)'
